# Generated by Django 3.0.5 on 2020-05-03 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='events.Event')),
                ('left_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_user_connections', to=settings.AUTH_USER_MODEL)),
                ('right_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_user_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
