# Generated by Django 3.0.5 on 2020-05-03 03:52

from datetime import datetime

from django.db import migrations


def populate_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    name = 'DIGITALKS EXPO 2020'
    start_date = datetime(2020, 5, 5)
    end_date = datetime(2020, 5, 5)
    description = '''

    Em 2019 foram 2 dias de evento com mais de 20 atividades, 11 auditórios com muito conteúdo e presença dos principais formadores de opinião do mercado nacional e internacional.

    DIGITAL ECONOMY | we’re under construction'
    '''

    Event.objects.create(name=name, description=description,
                         start_date=start_date, end_date=end_date)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_events),
    ]
